### ISSUE TITLE
Error due to wrong usage of t()

### ISSUE THREAD

**Issue by nhck** [bitpay/bitpay-drupalcommerce#8]
On a fresh install, once I choose the paypment method. I get this error:

> 	Recoverable fatal error: Argument 3 passed to t() must be of the type array, string given, called in /var/www/html/drupal7/sites/all/modules/commerce_bitpay/includes/commerce_bitpay.checkout.inc on line 122 and defined in t() (line 1730 of /var/www/html/drupal7/includes/bootstrap.inc).

**Comment by pieterpoorthuis** [comment]
I can reproduce on Drupal v7.56:
Recoverable fatal error: Argument 3 passed to t() must be of the type array, string given, called in /var/www/html/drupal7/sites/all/modules/commerce-bitpay/includes/commerce_bitpay.checkout.inc on line 122 and defined in t() (line 1735 of /var/www/html/drupal7/includes/bootstrap.inc).

We will work on a fix
