### ISSUE TITLE
Feature Request: Add proper Icons like the Paypal Commerce Module does.

### ISSUE THREAD

**Issue by nhck** [bitpay/bitpay-drupalcommerce#9]
It would look a bit more professional if there were proper icons at the checkout like the paypal_commerce module achieves: https://www.drupal.org/project/commerce_paypal

**Comment by warelordbud0141** [comment]
Well i here i dont know haw i did in but in here and ready to get payd

**Comment by pieterpoorthuis** [comment]
Logo is available here: https://github.com/bitpay/bitcoin-brand/blob/master/bitcoin.png

We will work on a fix.

**Comment by pieterpoorthuis** [comment]
Fixed in #10
